### ISSUE TITLE
Build service

### ISSUE THREAD

**Issue by jarnoweemen** [leprec0n/microservices#14]
In the feature workflow build individual service on pull request to development:
- [x] [Check if code changed](https://stackoverflow.com/questions/58136102/deploy-individual-services-from-a-monorepo-using-github-actions)
- [x] Only when base head is development.

Something like the following:
```yaml
on:
  pull_request:
    - 'service_x/**'
jobs:
  build: if ${{ github.base_ref == 'development' }}
```
